# Generated by Django 4.1 on 2022-08-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_livro_autores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='category',
            new_name='categoria',
        ),
    ]
